### ISSUE TITLE
Issue Report 

### ISSUE THREAD

**Issue by NeKoOuO** [RyensX/MediaBox#100]
Version:2.58(59)
Crash:java.lang.IllegalStateException: There are multiple DataStores active for the same file: /data/user/0/com.su.mediabox/files/datastore/plugin_pref_com.su.dubokuvideoplugin#863237f24cbf4c99634babbc61d11b078f41d2.preferences_pb. You should either maintain your DataStore as a singleton or confirm that there is no two DataStore's active on the same file (by confirming that the scope is cancelled).
	at androidx.datastore.core.SingleProcessDataStore$file$2.invoke(Unknown Source:77)
	at androidx.datastore.core.SingleProcessDataStore$file$2.invoke(Unknown Source:0)
	at kotlin.SynchronizedLazyImpl.getValue(Unknown Source:20)
	at androidx.datastore.core.SingleProcessDataStore.getFile(Unknown Source:2)
	at androidx.datastore.core.SingleProcessDataStore.readData(Unknown Source:68)
	at androidx.datastore.core.SingleProcessDataStore.readDataOrHandleCorruption(Unknown Source:92)
	at androidx.datastore.core.SingleProcessDataStore.readAndInit(Unknown Source:175)
	at androidx.datastore.core.SingleProcessDataStore.readAndInitOrPropagateFailure(Unknown Source:62)
	at androidx.datastore.core.SingleProcessDataStore.handleRead(Unknown Source:23)
	at androidx.datastore.core.SingleProcessDataStore.access$handleRead(Unknown Source:0)
	at androidx.datastore.core.SingleProcessDataStore$actor$3.invokeSuspend(Unknown Source:44)
	at androidx.datastore.core.SingleProcessDataStore$actor$3.invoke(Unknown Source:8)
	at androidx.datastore.core.SingleProcessDataStore$actor$3.invoke(Unknown Source:4)
	at androidx.datastore.core.SimpleActor$offer$2.invokeSuspend(Unknown Source:101)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3281388, Dispatchers.IO]

Phone:BOARD=cas
BOOTLOADER=unknown
BRAND=Xiaomi
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=cas
DISPLAY=SKQ1.211006.001 release-keys
FINGERPRINT=Xiaomi/cas/cas:12/RKQ1.211001.001/V13.0.4.0.SJJCNXM:user/release-keys
HARDWARE=qcom
HOST=xiaomi.eu
HW_TIMEOUT_MULTIPLIER=1
ID=SKQ1.211006.001
IS_CONTAINER=false
IS_DEBUGGABLE=false
IS_EMULATOR=false
IS_ENG=false
IS_MIUI=true
IS_TIMINGTRACE=false
IS_TREBLE_ENABLED=true
IS_USER=true
IS_USERDEBUG=false
MANUFACTURER=Xiaomi
MODEL=M2007J1SC
ODM_SKU=unknown
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=cas
RADIO=unknown
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=QTI
SOC_MODEL=SM8250
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@e3b0b1c
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@2e7325
SUPPORTED_ABIS=[Ljava.lang.String;@e7a7cfa
TAG=Build
TAGS=release-keys
TIME=1653325996000
TYPE=user
UNKNOWN=unknown
USER=builder

**Comment by RyensX** [comment]
重装插件
