### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by Winhaina** [RyensX/MediaBox#104]
Version:2.58(59)
Crash:java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{c45b1ee VFED.V... ......ID 0,0-1260,2268 #7f0a027b app:id/recycler_view}, adapter:androidx.preference.PreferenceGroupAdapter@3e90f08, layout:androidx.recyclerview.widget.LinearLayoutManager@50006a1, context:com.su.mediabox.view.activity.MainActivity@65404fc
	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(Unknown Source:20)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(Unknown Source:3)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(Unknown Source:18)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemChanged(Unknown Source:3)
	at androidx.preference.PreferenceGroupAdapter.onPreferenceChange(Unknown Source:9)
	at androidx.preference.Preference.notifyChanged(Unknown Source:4)
	at androidx.preference.Preference.setTitle(Unknown Source:10)
	at com.su.mediabox.view.preference.PreferenceDslKt.titleRes(Unknown Source:23)
	at com.su.mediabox.view.fragment.page.SettingsPageFragment$onCreatePreferences$1$5$1$2.invokeSuspend(Unknown Source:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4afe591, Dispatchers.IO]

Phone:BOARD=kalama
BOOTLOADER=unknown
BRAND=vivo
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=PD2338
DISPLAY=UP1A.231005.007 release-keys
FINGERPRINT=vivo/PD2338/PD2338:14/UP1A.231005.007/compiler04301702:user/release-keys
HARDWARE=qcom
HOST=comdg01146152
ID=UP1A.231005.007
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=vivo
MODEL=V2338A
ODM_SKU=unknown
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=PD2338
RADIO=unknown
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=QTI
SOC_MODEL=SM8550
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@4238fef
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@ad94afc
SUPPORTED_ABIS=[Ljava.lang.String;@e45e585
TAGS=release-keys
TIME=1714467753000
TYPE=user
UNKNOWN=unknown
USER=compiler

**Comment by RyensX** [comment]
已知问题
