### ISSUE TITLE
应用崩溃日志

### ISSUE THREAD

**Issue by TitoemX** [RyensX/MediaBox#110]
Version:2.62(62)
Crash:java.lang.IllegalArgumentException: Unknown URL content://downloads/my_downloads
	at android.content.ContentResolver.insert(ContentResolver.java:1840)
	at android.app.DownloadManager.enqueue(DownloadManager.java:1100)
	at com.su.mediabox.plugin.PluginManager.downloadPlugin(Unknown Source:135)
	at com.su.mediabox.view.viewcomponents.inner.PreviewPluginInfoViewHolder$special$$inlined$setOnClickListener$3.onClick(Unknown Source:51)
	at android.view.View.performClick(View.java:7322)
	at android.widget.CompoundButton.performClick(CompoundButton.java:148)
	at android.view.View.performClickInternal(View.java:7296)
	at android.view.View.access$3600(View.java:839)
	at android.view.View$PerformClick.run(View.java:28319)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8673)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

Phone:BOARD=TEL
BOOTLOADER=unknown
BRAND=HONOR
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=HWTEL-H
DISPLAY=TEL-AN00a 3.0.0.165(C00E165R4P2)
FINGERPRINT=HONOR/TEL-AN00a/HWTEL-H:10/HONORTEL-AN00a/103.0.0.165C00:user/release-keys
FINGERPRINTEX=HONOR/TEL-AN00a/HWTEL-H:10/HONORTEL-AN00a/103.0.0.165C00:user/release-keys
HARDWARE=kirin820
HOST=cn-central-hcd-2a-eb5f81d221681804423849-57ccc7794-7fh7w
HWFINGERPRINT=///TEL-LGRP1-CHN 3.0.0.165/TEL-AN00a-CUST 3.0.0.165(C00)/TEL-AN00a-PRELOAD 3.0.0.2(C00R4)//
ID=HONORTEL-AN00a
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=HUAWEI
MODEL=TEL-AN00a
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=TEL-AN00a
RADIO=21C93B391S000C000,21C93B391S000C000
SERIAL=unknown
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@d26eee0
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@79c2599
SUPPORTED_ABIS=[Ljava.lang.String;@e46d05e
TAGS=release-keys
TIME=1681807552000
TYPE=user
UNKNOWN=unknown
USER=test

**Comment by RyensX** [comment]
直接在软件内下载插件呢
