### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by avalon-plan** [RyensX/MediaBox#114]
Version:2.62(62)
Crash:java.lang.ExceptionInInitializerError
	at com.su.mxvideoplugin.MainPluginFactory.createComponent(MainPluginFactory.kt:23)
	at com.su.mediabox.plugin.PluginManager.acquireComponent(Unknown Source:45)
	at com.su.mediabox.viewmodel.MediaCombineSearchViewModel$special$$inlined$map$1$2.emit(Unknown Source:130)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:145)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Unknown Source:0)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@14dfcd4, Dispatchers.IO]
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property host has not been initialized
	at com.su.basevideopluginframework.framework.Const.getHost(Const.kt:9)
	at com.su.basevideopluginframework.framework.Const$hostUrl$2.invoke(Const.kt:11)
	at com.su.basevideopluginframework.framework.Const$hostUrl$2.invoke(Const.kt:10)
	at kotlin.SynchronizedLazyImpl.getValue(Unknown Source:20)
	at com.su.basevideopluginframework.framework.Const.getHostUrl(Const.kt:10)
	at com.su.basevideopluginframework.framework.Const.url(Const.kt:22)
	at com.su.mxvideoplugin.SearchPage.<clinit>(SearchPage.kt:17)
	... 14 more

Phone:BOARD=tb8796p1_64_sp
BOOTLOADER=unknown
BRAND=vivo
BRAND_FOR_ATTESTATION=unknown
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=DPD2329
DEVICE_FOR_ATTESTATION=unknown
DISPLAY=DPD2329_A_14.0.10.21.W10.V000L1
FINGERPRINT=vivo/DPD2329M/DPD2329:14/UP1A.231005.007/compiler10221935:user/release-keys
HARDWARE=mt8796
HOST=comdg01146226
HW_TIMEOUT_MULTIPLIER=1
ID=UP1A.231005.007
IS_ARC=false
IS_DEBUGGABLE=false
IS_EMULATOR=false
IS_ENG=false
IS_TREBLE_ENABLED=true
IS_USER=true
IS_USERDEBUG=false
MANUFACTURER=vivo
MANUFACTURER_FOR_ATTESTATION=unknown
MODEL=iPA2475
MODEL_FOR_ATTESTATION=unknown
MTK_HBT_ON_64BIT_ONLY_CHIP=true
MTK_HBT_SUPPORT=true
MTK_HBT_SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@7afcd48
MTK_HBT_SUPPORTED_ABIS=[Ljava.lang.String;@41687e1
ODM_SKU=1101110111
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=DPD2329M
PRODUCT_FOR_ATTESTATION=unknown
RADIO=unknown
RIGHTMODEL=DPD2350E
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=Mediatek
SOC_MODEL=MT8796
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@4049906
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@d392bc7
SUPPORTED_ABIS=[Ljava.lang.String;@f9875f4
TAG=Build
TAGS=release-keys
TIME=1729596701000
TYPE=user
UNKNOWN=unknown
USER=compiler
VIVO_ON_64BIT_ONLY_CHIP=false
VIVO_SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@692c11d
VIVO_SUPPORTED_ABIS=[Ljava.lang.String;@cc13f92
mZygoteConfigAdapter=com.vivo.adapter.internal.os.ZygoteConfigAdapterImpl@c92bd63
needModifyModelAppList=[cn.wps.moffice_eng, com.cpuid.cpu_z, com.finalwire.aida64, com.antutu.ABenchMark, com.ludashi.benchmark, com.tencent.mobileqq, com.qzone, com.tencent.karaoke, com.sina.weibo]

**Comment by RyensX** [comment]
更新插件试试
