### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by jingboyang123** [RyensX/MediaBox#15]
CrashInfo:
java.lang.NullPointerException: mUrl must not be null
	at com.su.mediabox.view.activity.y.onClick(:1)
	at android.view.View.performClick(View.java:5655)
	at android.view.View$PerformClick.run(View.java:22633)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:159)
	at android.app.ActivityThread.main(ActivityThread.java:6378)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1099)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by RyensX** [comment]
如何复现？
