### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by qertyuy** [RyensX/MediaBox#30]
CrashInfo:
java.lang.ClassCastException: com.su.mediabox.bean.MediaSearchHistory cannot be cast to com.su.mediabox.bean.DefaultEmpty
	at com.su.mediabox.view.viewcomponents.inner.DefaultEmptyViewHolder.onBind(Unknown Source:0)
	at com.su.mediabox.view.adapter.type.TypeViewHolder.onBind(Unknown Source:5)
	at com.su.mediabox.view.adapter.type.TypeAdapter.k(:1)
	at androidx.recyclerview.widget.RecyclerView$r.k(:64)
	at androidx.recyclerview.widget.RecyclerView$r.e(:1)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(:2)
	at androidx.recyclerview.widget.GridLayoutManager.v1(Unknown Source:94)
	at androidx.recyclerview.widget.LinearLayoutManager.g1(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.y0(:17)
	at androidx.recyclerview.widget.GridLayoutManager.y0(:7)
	at androidx.recyclerview.widget.RecyclerView.s(:2)
	at androidx.recyclerview.widget.RecyclerView.q(:7)
	at androidx.recyclerview.widget.RecyclerView.onLayout(:2)
	at android.view.View.layout(View.java:23727)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at com.scwang.smart.refresh.layout.SmartRefreshLayout.onLayout(:4)
	at android.view.View.layout(View.java:23727)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23727)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23727)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23727)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23727)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23727)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:866)
	at android.view.View.layout(View.java:23727)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4045)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3464)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2381)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9359)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1152)
	at android.view.Choreographer.doCallbacks(Choreographer.java:918)
	at android.view.Choreographer.doFrame(Choreographer.java:833)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1137)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8307)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by RyensX** [comment]
已知问题，后面修复
