### ISSUE TITLE
應用奔潰

### ISSUE THREAD

**Issue by Ryder233** [RyensX/MediaBox#36]
Version:2.3(42)
Crash:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.su.mediabox/com.su.mediabox.view.activity.MediaSearchActivity}: java.lang.RuntimeException: 获取当前插件信息错误！
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3767)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3934)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2314)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8256)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
Caused by: java.lang.RuntimeException: 获取当前插件信息错误！
	at com.su.mediabox.database.AppDatabaseKt.getAppDataBase(Unknown Source:25)
	at com.su.mediabox.viewmodel.MediaSearchViewModel.<init>(Unknown Source:29)
	at java.lang.Class.newInstance(Native Method)
	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(Unknown Source:2)
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(Unknown Source:123)
	at androidx.lifecycle.SavedStateViewModelFactory.create(Unknown Source:29)
	at androidx.lifecycle.ViewModelProvider.get(Unknown Source:32)
	at androidx.lifecycle.ViewModelProvider.get(Unknown Source:23)
	at androidx.lifecycle.ViewModelLazy.getValue(Unknown Source:31)
	at androidx.lifecycle.ViewModelLazy.getValue(Unknown Source:0)
	at com.su.mediabox.view.activity.MediaSearchActivity.getViewModel(Unknown Source:2)
	at com.su.mediabox.view.activity.MediaSearchActivity.onCreate(Unknown Source:194)
	at android.app.Activity.performCreate(Activity.java:8178)
	at android.app.Activity.performCreate(Activity.java:8146)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3740)
	... 12 more

Phone:BOARD=chopin
BOOTLOADER=unknown
BRAND=Redmi
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=chopin
DISPLAY=SP1A.210812.016
FINGERPRINT=Redmi/chopin/chopin:12/SP1A.210812.016/V13.0.4.0.SKPCNXM:user/release-keys
HARDWARE=mt6893
HOST=c5-xm-ota-bd018.bj
ID=SP1A.210812.016
IS_DEBUGGABLE=false
IS_EMULATOR=false
IS_MIUI=true
MANUFACTURER=Xiaomi
MODEL=M2104K10AC
ODM_SKU=chopin
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=chopin
RADIO=unknown
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=Mediatek
SOC_MODEL=MT6891
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@94e81ac
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@8f7ce75
SUPPORTED_ABIS=[Ljava.lang.String;@5e8be0a
TAGS=release-keys
TIME=1647753533000
TYPE=user
UNKNOWN=unknown
USER=builder

**Comment by RyensX** [comment]
搜索的时候崩溃？具体是如何出现的？
