### ISSUE TITLE
后台再切回来时调用glyma影视失败

### ISSUE THREAD

**Issue by wsb1227427607** [RyensX/MediaBox#37]
Version:2.3(42)
Crash:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.su.mediabox/com.su.mediabox.view.activity.MediaSearchActivity}: java.lang.RuntimeException: 获取当前插件信息错误！
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3949)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2327)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8301)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
Caused by: java.lang.RuntimeException: 获取当前插件信息错误！
	at com.su.mediabox.database.AppDatabaseKt.getAppDataBase(Unknown Source:25)
	at com.su.mediabox.viewmodel.MediaSearchViewModel.<init>(Unknown Source:29)
	at java.lang.Class.newInstance(Native Method)
	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(Unknown Source:2)
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(Unknown Source:123)
	at androidx.lifecycle.SavedStateViewModelFactory.create(Unknown Source:29)
	at androidx.lifecycle.ViewModelProvider.get(Unknown Source:32)
	at androidx.lifecycle.ViewModelProvider.get(Unknown Source:23)
	at androidx.lifecycle.ViewModelLazy.getValue(Unknown Source:31)
	at androidx.lifecycle.ViewModelLazy.getValue(Unknown Source:0)
	at com.su.mediabox.view.activity.MediaSearchActivity.getViewModel(Unknown Source:2)
	at com.su.mediabox.view.activity.MediaSearchActivity.onCreate(Unknown Source:194)
	at android.app.Activity.performCreate(Activity.java:8181)
	at android.app.Activity.performCreate(Activity.java:8147)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
	... 12 more

Phone:BOARD=matisse
BOOTLOADER=unknown
BRAND=Redmi
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=matisse
DISPLAY=SP1A.210812.016
FINGERPRINT=Redmi/matisse/matisse:12/SP1A.210812.016/V13.0.2.0.SLKCNXM:user/release-keys
HARDWARE=mt6983
HOST=m1-xm-ota-bd355.bj.idc.xiaomi.com
ID=SP1A.210812.016
IS_DEBUGGABLE=false
IS_EMULATOR=false
IS_MIUI=true
MANUFACTURER=Xiaomi
MODEL=22011211C
ODM_SKU=matisse
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=matisse
RADIO=unknown
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=Mediatek
SOC_MODEL=MT6983
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@50a923f
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@9c9a70c
SUPPORTED_ABIS=[Ljava.lang.String;@b09f855
TAGS=release-keys
TIME=1646404952000
TYPE=user
UNKNOWN=unknown
USER=builder

**Comment by RyensX** [comment]
只有这个插件出现这个情况？

**Comment by MARVEL-LJH** [comment]
插件已经更新最新的api，是否还出现相同情况？此情况只是偶尔出现？
