### ISSUE TITLE
应用崩溃

### ISSUE THREAD

**Issue by haiyan08** [RyensX/MediaBox#55]
Version:2.44(47)
Crash:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.su.mediabox/com.su.mediabox.view.activity.MediaSearchActivity}: java.lang.RuntimeException: 获取当前插件信息错误！
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.RuntimeException: 获取当前插件信息错误！
	at com.su.mediabox.database.AppDatabaseKt.getAppDataBase(Unknown Source:25)
	at com.su.mediabox.viewmodel.MediaSearchViewModel.<init>(Unknown Source:29)
	at java.lang.Class.newInstance(Native Method)
	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(Unknown Source:2)
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(Unknown Source:123)
	at androidx.lifecycle.SavedStateViewModelFactory.create(Unknown Source:29)
	at androidx.lifecycle.ViewModelProvider.get(Unknown Source:32)
	at androidx.lifecycle.ViewModelProvider.get(Unknown Source:23)
	at androidx.lifecycle.ViewModelLazy.getValue(Unknown Source:31)
	at androidx.lifecycle.ViewModelLazy.getValue(Unknown Source:0)
	at com.su.mediabox.view.activity.MediaSearchActivity.getViewModel(Unknown Source:2)
	at com.su.mediabox.view.activity.MediaSearchActivity.onCreate(Unknown Source:202)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Activity.performCreate(Activity.java:7880)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
	... 11 more

Phone:BOARD=sdm845
BOOTLOADER=unknown
BRAND=Xiaomi
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=dipper
DISPLAY=QKQ1.190828.002 test-keys
FINGERPRINT=Xiaomi/dipper/dipper:10/QKQ1.190828.002/V12.5.2.0.QEACNXM:user/release-keys
HARDWARE=qcom
HOST=c5-miui-ota-bd38.bj
ID=QKQ1.190828.002
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=Xiaomi
MODEL=MI 8
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=dipper
RADIO=unknown
SERIAL=unknown
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@ffca4c1
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@70b2466
SUPPORTED_ABIS=[Ljava.lang.String;@1b9c3a7
TAGS=release-keys
TIME=1635404500000
TYPE=user
UNKNOWN=unknown
USER=builder

**Comment by RyensX** [comment]
是在什么情况下触发的
