### ISSUE TITLE
应用崩溃

### ISSUE THREAD

**Issue by chgf573** [RyensX/MediaBox#57]
Version:2.5(48)
Crash:java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{b60f4f8 VFED.V... ......ID 0,0-1080,1949 #7f0a0275 app:id/recycler_view}, adapter:androidx.preference.PreferenceGroupAdapter@65693d3, layout:androidx.recyclerview.widget.LinearLayoutManager@c196b10, context:com.su.mediabox.view.activity.MainActivity@c0aca4e
	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(Unknown Source:20)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(Unknown Source:3)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(Unknown Source:18)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemChanged(Unknown Source:3)
	at androidx.preference.PreferenceGroupAdapter.onPreferenceChange(Unknown Source:9)
	at androidx.preference.Preference.notifyChanged(Unknown Source:4)
	at androidx.preference.Preference.setTitle(Unknown Source:10)
	at com.su.mediabox.util.PreferenceDslKt.titleRes(Unknown Source:23)
	at com.su.mediabox.view.fragment.page.SettingsPageFragment$onCreatePreferences$1$5$1$2.invokeSuspend(Unknown Source:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@30cde83, Dispatchers.IO]

Phone:BOARD=kona
BOOTLOADER=unknown
BRAND=OnePlus
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=OnePlus9R
DISPLAY=LE2100_11_F.07
FINGERPRINT=OnePlus/OnePlus9R_CH/OnePlus9R:13/TP1A.220905.001/R.a2f826-2+1:user/release-keys
HARDWARE=qcom
HOST=dg02-pool03-kvm15
ID=TP1A.220905.001
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=OnePlus
MODEL=LE2100
ODM_SKU=unknown
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=OnePlus9R_CH
RADIO=unknown
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=Qualcomm
SOC_MODEL=SM8250
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@95524d9
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@350fe9e
SUPPORTED_ABIS=[Ljava.lang.String;@344bd7f
TAGS=release-keys
TIME=1663070451000
TYPE=user
UNKNOWN=unknown
USER=root

**Comment by RyensX** [comment]
崩溃的场景是？
