### ISSUE TITLE
出bug

### ISSUE THREAD

**Issue by wjb011213** [RyensX/MediaBox#58]
Version:2.5(48)
Crash:java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{ef84ff2 VFED.V... ......ID 0,0-1440,2516 #7f0a0275 app:id/recycler_view}, adapter:androidx.preference.PreferenceGroupAdapter@4aac86b, layout:androidx.recyclerview.widget.LinearLayoutManager@38a1fc8, context:com.su.mediabox.view.activity.MainActivity@57796ff
	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(Unknown Source:20)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(Unknown Source:3)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(Unknown Source:18)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemChanged(Unknown Source:3)
	at androidx.preference.PreferenceGroupAdapter.onPreferenceChange(Unknown Source:9)
	at androidx.preference.Preference.notifyChanged(Unknown Source:4)
	at androidx.preference.Preference.setTitle(Unknown Source:10)
	at com.su.mediabox.util.PreferenceDslKt.titleRes(Unknown Source:23)
	at com.su.mediabox.view.fragment.page.SettingsPageFragment$onCreatePreferences$1$5$1$2.invokeSuspend(Unknown Source:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f49215b, Dispatchers.IO]

Phone:BOARD=kona
BOOTLOADER=unknown
BRAND=OPPO
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=OP4A7A
DISPLAY=PDEM30_11_F.21
FINGERPRINT=OPPO/PDEM30/OP4A7A:12/RKQ1.211103.002/Q.202208101905:user/release-keys
HARDWARE=qcom
HOST=dg02-pool03-kvm282
ID=RKQ1.211103.002
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=OPPO
MODEL=PDEM30
ODM_SKU=unknown
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=PDEM30
RADIO=unknown
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=Qualcomm
SOC_MODEL=SM8250
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@14dac05
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@959f45a
SUPPORTED_ABIS=[Ljava.lang.String;@b5ca68b
TAGS=release-keys
TIME=1659690498000
TYPE=user
UNKNOWN=unknown
USER=root

**Comment by RyensX** [comment]
已知问题，你这个是在什么情况下出现的？

**Comment by wjb011213** [comment]
> 已知问题，你这个是在什么情况下出现的？

不是特别清楚，就是单纯打开后，突然出现的

**Comment by RyensX** [comment]
> > 已知问题，你这个是在什么情况下出现的？
> 
> 不是特别清楚，就是单纯打开后，突然出现的

试试最新的测试版还会不会
