### ISSUE TITLE
T

### ISSUE THREAD

**Issue by Weishile** [RyensX/MediaBox#60]
Version:2.5(48)
Crash:android.view.WindowManager$InvalidDisplayException: Unable to add window android.view.OplusViewRootImplHooks$ColorW@e375efe -- the specified display can not be found
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1379)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:405)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)
	at android.widget.ToastPresenter.addToastView(ToastPresenter.java:306)
	at android.widget.ToastPresenter.show(ToastPresenter.java:231)
	at android.widget.ToastPresenter.show(ToastPresenter.java:214)
	at android.widget.Toast$TN.handleShow(Toast.java:702)
	at android.widget.Toast$TN$1.handleMessage(Toast.java:634)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8355)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

Phone:BOARD=kona
BOOTLOADER=unknown
BRAND=OnePlus
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=OnePlus8
DISPLAY=IN2010_11_F.10
FINGERPRINT=OnePlus/OnePlus8_CH/OnePlus8:13/RKQ1.211119.001/Q.202210030833:user/release-keys
HARDWARE=qcom
HOST=dg02-pool03-kvm236
ID=RKQ1.211119.001
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=OnePlus
MODEL=IN2010
ODM_SKU=unknown
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=OnePlus8_CH
RADIO=unknown
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=Qualcomm
SOC_MODEL=SM8250
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@12c0759
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@1d26f1e
SUPPORTED_ABIS=[Ljava.lang.String;@3a8a3ff
TAGS=release-keys
TIME=1665196989000
TYPE=user
UNKNOWN=unknown
USER=root

**Comment by RyensX** [comment]
具体说在做什么时触发的？

**Comment by Weishile** [comment]
在切换应用的时候

Ryens ***@***.***> 于 2022年10月15日周六 16:59写道：
