### ISSUE TITLE
crash log

### ISSUE THREAD

**Issue by smarttommyau** [RyensX/MediaBox#61]
Version:2.51(49)
Crash:android.database.CursorWindowAllocationException: Could not allocate CursorWindow '/data/user/0/com.su.mediabox/databases/media_plugin_data_com.su.sakuraanime2plugin#863237f24cbf4c99634babbc61d11b078f41d2.db' of size 2097152 due to error -24.
	at android.database.CursorWindow.nativeCreate(Native Method)
	at android.database.CursorWindow.<init>(CursorWindow.java:139)
	at android.database.CursorWindow.<init>(CursorWindow.java:120)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:202)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:147)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
	at androidx.room.InvalidationTracker$1.checkUpdatedTable(Unknown Source:20)
	at androidx.room.InvalidationTracker$1.run(Unknown Source:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

Phone:BOARD=BAH3-W59
BOOTLOADER=unknown
BRAND=HUAWEI
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=HWBAH3-H
DISPLAY=BAH3-W59 2.0.0.250(C636E1R1P1)
FINGERPRINT=HUAWEI/BAH3-W59NM/HWBAH3-H:10/HUAWEIBAH3-W59/102.0.0.250C636:user/release-keys
FINGERPRINTEX=HUAWEI/BAH3-W59NM/HWBAH3-H:10/HUAWEIBAH3-W59/102.0.0.250C636:user/release-keys
HARDWARE=kirin820
HOST=cn-central-hcd-2a-3f35cfb661656639379956-59448c8987-kchqr
HWFINGERPRINT=///BAH3-LGRP8-OVS 2.0.0.250/BAH3-W59-CUST 2.0.0.1(C636)/BAH3-W59-PRELOAD 2.0.0.1(C636R1)//
ID=HUAWEIBAH3-W59
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=HUAWEI
MODEL=BAH3-W59
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=BAH3-W59NM
RADIO=unknown
SERIAL=unknown
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@4b739cd
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@72e4282
SUPPORTED_ABIS=[Ljava.lang.String;@9821d93
TAGS=release-keys
TIME=1656643489000
TYPE=user
UNKNOWN=unknown
USER=test

**Comment by RyensX** [comment]
具体触发场景？
清除数据还会？

**Comment by smarttommyau** [comment]
在看影片是突然停了，然后回到影片詳情页后，在点进影片，就crash了。
清理后台后，再重开应用就回复正常。

**Comment by RyensX** [comment]
你这个情况我无法复现，具体什么插件什么视频我试试？

**Comment by smarttommyau** [comment]
樱花动漫2，间谍过家家，好像是第12集。应该是 utils/dlna/dms/MediaContentDao.kt 的 moveToNext 时返回的那一行的大小过大，结果炸了

**Comment by smarttommyau** [comment]
又或是因为cursor没有关掉而导致的问题

**Comment by RyensX** [comment]
你说播放时是指投屏播放？

**Comment by RyensX** [comment]
> 又或是因为cursor没有关掉而导致的问题，加一行cursor.close() 可能可以解决到问题

这个是在use{}内使用的，只是不知道为什么过长了

**Comment by RyensX** [comment]
可能你在这个插件db上记录太多了（比如很多播放历史），然后内存又不太够就OOM了。不过在播放时触发我不太理解
