### ISSUE TITLE
crash log

### ISSUE THREAD

**Issue by smarttommyau** [RyensX/MediaBox#63]
Version:2.51(49)
Crash:java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{877433c VFED.V... ......ID 0,0-2000,904 #7f0a0277 app:id/recycler_view}, adapter:androidx.preference.PreferenceGroupAdapter@194cbbe, layout:androidx.recyclerview.widget.LinearLayoutManager@562d41f, context:com.su.mediabox.view.activity.MainActivity@cb32f68
	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(Unknown Source:20)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(Unknown Source:3)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(Unknown Source:18)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemChanged(Unknown Source:3)
	at androidx.preference.PreferenceGroupAdapter.onPreferenceChange(Unknown Source:9)
	at androidx.preference.Preference.notifyChanged(Unknown Source:4)
	at androidx.preference.Preference.setTitle(Unknown Source:10)
	at com.su.mediabox.util.PreferenceDslKt.titleRes(Unknown Source:23)
	at com.su.mediabox.view.fragment.page.SettingsPageFragment$onCreatePreferences$1$5$1$2.invokeSuspend(Unknown Source:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@dffbde, Dispatchers.IO]

Phone:BOARD=BAH3-W59
BOOTLOADER=unknown
BRAND=HUAWEI
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=HWBAH3-H
DISPLAY=BAH3-W59 2.0.0.250(C636E1R1P1)
FINGERPRINT=HUAWEI/BAH3-W59NM/HWBAH3-H:10/HUAWEIBAH3-W59/102.0.0.250C636:user/release-keys
FINGERPRINTEX=HUAWEI/BAH3-W59NM/HWBAH3-H:10/HUAWEIBAH3-W59/102.0.0.250C636:user/release-keys
HARDWARE=kirin820
HOST=cn-central-hcd-2a-3f35cfb661656639379956-59448c8987-kchqr
HWFINGERPRINT=///BAH3-LGRP8-OVS 2.0.0.250/BAH3-W59-CUST 2.0.0.1(C636)/BAH3-W59-PRELOAD 2.0.0.1(C636R1)//
ID=HUAWEIBAH3-W59
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=HUAWEI
MODEL=BAH3-W59
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=BAH3-W59NM
RADIO=unknown
SERIAL=unknown
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@d175d7c
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@b56c605
SUPPORTED_ABIS=[Ljava.lang.String;@126065a
TAGS=release-keys
TIME=1656643489000
TYPE=user
UNKNOWN=unknown
USER=test

**Comment by smarttommyau** [comment]
打开应用时弹出，刷新后就没事了

**Comment by RyensX** [comment]
这个是已知bug，只是我还没去解决
