### ISSUE TITLE
切换后台后报错

### ISSUE THREAD

**Issue by qqyc** [RyensX/MediaBox#65]
Version:2.51(49)
Crash:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.su.mediabox/com.su.mediabox.view.activity.MediaSearchActivity}: java.lang.RuntimeException: 获取当前插件信息错误！
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4111)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4277)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.RuntimeException: 获取当前插件信息错误！
	at com.su.mediabox.database.AppDatabaseKt.getAppDataBase(Unknown Source:25)
	at com.su.mediabox.viewmodel.MediaSearchViewModel.<init>(Unknown Source:29)
	at java.lang.Class.newInstance(Native Method)
	at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(Unknown Source:2)
	at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(Unknown Source:123)
	at androidx.lifecycle.SavedStateViewModelFactory.create(Unknown Source:29)
	at androidx.lifecycle.ViewModelProvider.get(Unknown Source:32)
	at androidx.lifecycle.ViewModelProvider.get(Unknown Source:23)
	at androidx.lifecycle.ViewModelLazy.getValue(Unknown Source:31)
	at androidx.lifecycle.ViewModelLazy.getValue(Unknown Source:0)
	at com.su.mediabox.view.activity.MediaSearchActivity.getViewModel(Unknown Source:2)
	at com.su.mediabox.view.activity.MediaSearchActivity.onCreate(Unknown Source:202)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8270)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4085)
	... 12 more

Phone:BOARD=lahaina
BOOTLOADER=G9980ZCS2CVI4
BRAND=samsung
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=p3q
DISPLAY=SP1A.210812.016.G9980ZCS2CVI4
FINGERPRINT=samsung/p3qzcx/p3q:12/SP1A.210812.016/G9980ZCS2CVI4:user/release-keys
HARDWARE=qcom
HOST=21DJ6B20
ID=SP1A.210812.016
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=samsung
MODEL=SM-G9980
ODM_SKU=unknown
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=p3qzcx
RADIO=unknown
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=QTI
SOC_MODEL=SM8350
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@7087eed
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@d987122
SUPPORTED_ABIS=[Ljava.lang.String;@eacb7b3
TAGS=release-keys
TIME=1664158973000
TYPE=user
UNKNOWN=unknown
USER=dpi

**Comment by RyensX** [comment]
偶尔触发？
