### ISSUE TITLE
崩溃日志

### ISSUE THREAD

**Issue by KazilanBigAss** [RyensX/MediaBox#69]
Version:2.53(53)
Crash:java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{81d5b8b VFED.V... ......ID 0,0-2322,656 #7f0a027a app:id/recycler_view}, adapter:androidx.preference.PreferenceGroupAdapter@d3d63bd, layout:androidx.recyclerview.widget.LinearLayoutManager@8b53db2, context:com.su.mediabox.view.activity.MainActivity@292848d
	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(Unknown Source:20)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(Unknown Source:3)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(Unknown Source:18)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemChanged(Unknown Source:3)
	at androidx.preference.PreferenceGroupAdapter.onPreferenceChange(Unknown Source:9)
	at androidx.preference.Preference.notifyChanged(Unknown Source:4)
	at androidx.preference.Preference.setTitle(Unknown Source:10)
	at com.su.mediabox.view.preference.PreferenceDslKt.titleRes(Unknown Source:23)
	at com.su.mediabox.view.fragment.page.SettingsPageFragment$onCreatePreferences$1$5$1$2.invokeSuspend(Unknown Source:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3fa79cc, Dispatchers.IO]

Phone:BOARD=rubens
BOOTLOADER=unknown
BRAND=Redmi
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=rubens
DISPLAY=SP1A.210812.016
FINGERPRINT=Redmi/rubens/rubens:12/SP1A.210812.016/V13.0.23.0.SLNCNXM:user/release-keys
HARDWARE=mt6895
HOST=m1-xm-ota-bd307.bj.idc.xiaomi.com
ID=SP1A.210812.016
IS_DEBUGGABLE=false
IS_EMULATOR=false
IS_MIUI=true
MANUFACTURER=Xiaomi
MODEL=22041211AC
ODM_SKU=rubens
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=rubens
RADIO=unknown
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=Mediatek
SOC_MODEL=MT6895Z/TCZA
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@1496dfe
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@c3b695f
SUPPORTED_ABIS=[Ljava.lang.String;@de0ffac
TAGS=release-keys
TIME=1662296110000
TYPE=user
UNKNOWN=unknown
USER=builder

**Comment by RyensX** [comment]
在设置触发的？
