### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Mayonij** [RyensX/MediaBox#73]
Version:2.54(55)
Crash:java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{74472cc VFED.V... ......ID 0,0-1080,1993 #7f0a027a app:id/recycler_view}, adapter:androidx.preference.PreferenceGroupAdapter@c77c4f7, layout:androidx.recyclerview.widget.LinearLayoutManager@b0c4f64, context:com.su.mediabox.view.activity.MainActivity@803bb0e
	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(Unknown Source:20)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(Unknown Source:3)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(Unknown Source:18)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemChanged(Unknown Source:3)
	at androidx.preference.PreferenceGroupAdapter.onPreferenceChange(Unknown Source:9)
	at androidx.preference.Preference.notifyChanged(Unknown Source:4)
	at androidx.preference.Preference.setTitle(Unknown Source:10)
	at com.su.mediabox.view.preference.PreferenceDslKt.titleRes(Unknown Source:23)
	at com.su.mediabox.view.fragment.page.SettingsPageFragment$onCreatePreferences$1$5$1$2.invokeSuspend(Unknown Source:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ff60c38, Dispatchers.IO]

Phone:BOARD=taro
BOOTLOADER=unknown
BRAND=Xiaomi
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=cupid
DISPLAY=TKQ1.220807.001 test-keys
FINGERPRINT=Xiaomi/cupid/cupid:13/TKQ1.220807.001/V14.0.4.0.TLCCNXM:user/release-keys
HARDWARE=qcom
HOST=pangu-build-component-system-39890-2rpzs-061f0-hl2xr
ID=TKQ1.220807.001
IS_DEBUGGABLE=false
IS_EMULATOR=false
IS_MIUI=true
MANUFACTURER=Xiaomi
MODEL=2201123C
ODM_SKU=cupid
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=cupid
RADIO=unknown
SERIAL=unknown
SKU=cupid
SOC_MANUFACTURER=QTI
SOC_MODEL=SM8450
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@f16e372
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@237c3c3
SUPPORTED_ABIS=[Ljava.lang.String;@b35f440
TAGS=release-keys
TIME=1673206834000
TYPE=user
UNKNOWN=unknown
USER=builder

>

**Comment by RyensX** [comment]
已知bug
