### ISSUE TITLE
503

### ISSUE THREAD

**Issue by Jonnyan404** [RyensX/MediaBox#77]
建议可以自定义域名,
以便挂了可以自己更换

**Comment by RyensX** [comment]
换成哪个域名了

**Comment by RyensX** [comment]
这个功能可以由插件实现的

**Comment by RyensX** [comment]
看了一个是又加了cloudflare
以前也加过一次后来又取消了

**Comment by Jonnyan404** [comment]
http://www.yinghuacd.com/
http://www.yhdmz.net/
https://www.yhdmp.cc/
https://yhdm.nl/

---

还有很多,看起来都差不多一个模板,有些加了  cloudflare  有些没有

**Comment by Jonnyan404** [comment]
对了,目前资源最牛的,
个人还是觉得  https://www.duboku.tv/   独领风骚,
可以试试整一个

**Comment by RyensX** [comment]
我晚点看看。如果你有空也可以试试适配一下源，wiki上有具体教程，很快的

**Comment by RyensX** [comment]
修改了，更新一下插件试试

**Comment by Jonnyan404** [comment]
```
Version:2.54(55)
Crash:java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.su.mediabox.util.update.AppUpdateHelper.noticeUpdate(Unknown Source:132)
	at com.su.mediabox.view.fragment.page.SettingsPageFragment.onCreatePreferences$lambda-40$lambda-39$lambda-29$lambda-28$lambda-27(Unknown Source:51)
	at com.su.mediabox.view.fragment.page.SettingsPageFragment.i(Unknown Source:0)
	at com.su.mediabox.view.fragment.page.f.onChanged(Unknown Source:8)
	at androidx.lifecycle.LiveData.considerNotify(Unknown Source:29)
	at androidx.lifecycle.LiveData.dispatchingValue(Unknown Source:44)
	at androidx.lifecycle.LiveData.setValue(Unknown Source:14)
	at androidx.lifecycle.MutableLiveData.setValue(Unknown Source:0)
	at androidx.lifecycle.LiveData$1.run(Unknown Source:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

Phone:BOARD=apollo
BOOTLOADER=unknown
BRAND=Redmi
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=apollo
DISPLAY=RKQ1.200826.002 test-keys
FINGERPRINT=Redmi/apollo/apollo:11/RKQ1.200826.002/V12.5.8.0.RJDCNXM:user/release-keys
HARDWARE=qcom
HOST=m1-xm-ota-bd149.bj.idc.xiaomi.com
ID=RKQ1.200826.002
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=Xiaomi
MODEL=M2007J3SC
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=apollo
RADIO=unknown
SERIAL=unknown
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@c9e0258
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@c0dffb1
SUPPORTED_ABIS=[Ljava.lang.String;@9c3fc96
TAGS=release-keys
TIME=1638768279000
TYPE=user
UNKNOWN=unknown
USER=builder
```

疯狂崩溃

**Comment by RyensX** [comment]
稍等，这是因为我在更新release的下载链接

**Comment by Jonnyan404** [comment]
> 稍等，这是因为我在更新release的下载链接

好的

**Comment by RyensX** [comment]
> > 稍等，这是因为我在更新release的下载链接
> 
> 好的

现在好了

**Comment by RyensX** [comment]
> 对了,目前资源最牛的,
> 个人还是觉得  https://www.duboku.tv/   独领风骚,
> 可以试试整一个

忘了说已上线
https://github.com/RyensX/DubokuVideoPlugin

**Comment by Jonnyan404** [comment]
> > 对了,目前资源最牛的,
> > 个人还是觉得  https://www.duboku.tv/   独领风骚,
> > 可以试试整一个
> 
> 忘了说已上线 https://github.com/RyensX/DubokuVideoPlugin

哈哈哈哈  第一时间就在tg群里看到了.
