### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by A3148475824** [RyensX/MediaBox#79]
Version:2.55(56)
Crash:java.lang.IllegalArgumentException: Unknown URL content://downloads/my_downloads
	at android.content.ContentResolver.insert(ContentResolver.java:2189)
	at android.content.ContentResolver.insert(ContentResolver.java:2155)
	at android.app.DownloadManager.enqueue(DownloadManager.java:1627)
	at com.su.mediabox.plugin.PluginManager.downloadPlugin(Unknown Source:135)
	at com.su.mediabox.view.viewcomponents.inner.PreviewPluginInfoViewHolder$special$$inlined$setOnClickListener$3.onClick(Unknown Source:51)
	at android.view.View.performClick(View.java:7751)
	at android.widget.CompoundButton.performClick(CompoundButton.java:146)
	at android.view.View.performClickInternal(View.java:7724)
	at android.view.View.access$3700(View.java:858)
	at android.view.View$PerformClick.run(View.java:29332)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8274)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

Phone:BOARD=cezanne
BOOTLOADER=unknown
BRAND=Redmi
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=cezanne
DISPLAY=SP1A.210812.016
FINGERPRINT=Redmi/cezanne/cezanne:12/SP1A.210812.016/V13.0.3.0.SJNCNXM:user/release-keys
HARDWARE=mt6889
HOST=m1-xm-ota-bd117.bj.idc.xiaomi.com
ID=SP1A.210812.016
IS_DEBUGGABLE=false
IS_EMULATOR=false
IS_MIUI=true
MANUFACTURER=Xiaomi
MODEL=M2006J10C
ODM_SKU=unknown
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=cezanne
RADIO=unknown
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=Mediatek
SOC_MODEL=MT6889Z/CZA
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@d2b32ce
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@e3395ef
SUPPORTED_ABIS=[Ljava.lang.String;@97fd8fc
TAGS=release-keys
TIME=1658936448000
TYPE=user
UNKNOWN=unknown
USER=builder

**Comment by RyensX** [comment]
试试直接内部安装
