### ISSUE TITLE
独播库崩溃😭

### ISSUE THREAD

**Issue by Afire-625** [RyensX/MediaBox#82]
Version:2.55(56)
Crash:java.lang.IllegalStateException: There are multiple DataStores active for the same file: /data/user/0/com.su.mediabox/files/datastore/plugin_pref_com.su.dubokuvideoplugin#863237f24cbf4c99634babbc61d11b078f41d2.preferences_pb. You should either maintain your DataStore as a singleton or confirm that there is no two DataStore's active on the same file (by confirming that the scope is cancelled).
	at androidx.datastore.core.SingleProcessDataStore$file$2.invoke(Unknown Source:77)
	at androidx.datastore.core.SingleProcessDataStore$file$2.invoke(Unknown Source:0)
	at kotlin.SynchronizedLazyImpl.getValue(Unknown Source:20)
	at androidx.datastore.core.SingleProcessDataStore.getFile(Unknown Source:2)
	at androidx.datastore.core.SingleProcessDataStore.readData(Unknown Source:68)
	at androidx.datastore.core.SingleProcessDataStore.readDataOrHandleCorruption(Unknown Source:92)
	at androidx.datastore.core.SingleProcessDataStore.readAndInit(Unknown Source:175)
	at androidx.datastore.core.SingleProcessDataStore.readAndInitOrPropagateFailure(Unknown Source:62)
	at androidx.datastore.core.SingleProcessDataStore.handleRead(Unknown Source:23)
	at androidx.datastore.core.SingleProcessDataStore.access$handleRead(Unknown Source:0)
	at androidx.datastore.core.SingleProcessDataStore$actor$3.invokeSuspend(Unknown Source:44)
	at androidx.datastore.core.SingleProcessDataStore$actor$3.invoke(Unknown Source:8)
	at androidx.datastore.core.SingleProcessDataStore$actor$3.invoke(Unknown Source:4)
	at androidx.datastore.core.SimpleActor$offer$2.invokeSuspend(Unknown Source:101)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@92319f0, Dispatchers.IO]

Phone:BOARD=kona
BOOTLOADER=unknown
BRAND=vivo
CPU_ABI=arm64-v8a
CPU_ABI2=
DEVICE=PD2024
DISPLAY=SP1A.210812.003 release-keys
FINGERPRINT=vivo/PD2024/PD2024:12/SP1A.210812.003/compiler10201706:user/release-keys
HARDWARE=qcom
HOST=comsz01078102
ID=SP1A.210812.003
IS_DEBUGGABLE=false
IS_EMULATOR=false
MANUFACTURER=vivo
MODEL=V2024A
ODM_SKU=111100101011
PERMISSIONS_REVIEW_REQUIRED=true
PRODUCT=PD2024
RADIO=unknown
SERIAL=unknown
SKU=unknown
SOC_MANUFACTURER=Qualcomm
SOC_MODEL=SM8250
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@2b5fc47
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@443c74
SUPPORTED_ABIS=[Ljava.lang.String;@d31459d
TAGS=release-keys
TIME=1666256609000
TYPE=user
UNKNOWN=unknown
USER=compiler

**Comment by RyensX** [comment]
删掉插件重装解决
